ITEM.name = "A Backpack"
ITEM.description = "A bag to hold items."
ITEM.model = "models/props_clutter/pouch.mdl"
ITEM.category = "Storage"
ITEM.width = 3
ITEM.height = 4
ITEM.invWidth = 7
ITEM.invHeight = 7
ITEM.isBag = true
ITEM.flag = "i"