ITEM.name = "A Hiking Bag"
ITEM.description = "A bag to hold items."
ITEM.model = "models/props_clutter/pouch.mdl"
ITEM.category = "Storage"
ITEM.width = 1
ITEM.height = 2
ITEM.invWidth = 2
ITEM.invHeight = 2
ITEM.isBag = true
ITEM.flag = "i"