ITEM.name = "Satchel"
ITEM.description = "A bag to hold items."
ITEM.model = "models/props_clutter/pouch.mdl"
ITEM.category = "Storage"
ITEM.width = 3
ITEM.height = 3
ITEM.invWidth = 5
ITEM.invHeight = 4
ITEM.isBag = true
ITEM.flag = "i"