ITEM.name = "A Small Backpack"
ITEM.description = "A bag to hold items."
ITEM.model = "models/props_clutter/pouch.mdl"
ITEM.category = "Storage"
ITEM.width = 4
ITEM.height = 4
ITEM.invWidth = 6
ITEM.invHeight = 6
ITEM.isBag = true
ITEM.flag = "i"