ITEM.name = "Medical Officer Uniform"
ITEM.description = "Standard Issue Uniform for Medical Officers"
ITEM.category = "Clothing"
ITEM.outfitCategory = "Clothing"
ITEM.flag = "c"
ITEM.model = "models/weapons/w_package.mdl"
ITEM.replacement = "models/fptp_786th_med.mdl"