ITEM.name = "Heldane Clothes"
ITEM.description = "Some clothing"
ITEM.category = "Clothing"
ITEM.outfitCategory = "Clothing"
ITEM.flag = "c"
ITEM.model = "models/weapons/w_package.mdl"
ITEM.replacement = "models/heldane.mdl"