ITEM.name = "Whiteshield Uniform"
ITEM.description = "Standard Issue Uniform for Whiteshields"
ITEM.category = "Clothing"
ITEM.outfitCategory = "Clothing"
ITEM.flag = "c"
ITEM.model = "models/weapons/w_package.mdl"
ITEM.replacement = "models/fptp_786th_ws.mdl"