ITEM.name = "Muschi Conscript Clothes"
ITEM.description = "Some clothing"
ITEM.category = "Clothing"
ITEM.outfitCategory = "Clothing"
ITEM.flag = "c"
ITEM.model = "models/weapons/w_package.mdl"
ITEM.replacement = "models/knight_ig/muschi_ig_conscript.mdl"