ITEM.name = "Cultist Clothes1"
ITEM.description = "Some clothing"
ITEM.category = "Clothing"
ITEM.outfitCategory = "Clothing"
ITEM.flag = "c"
ITEM.model = "models/weapons/w_package.mdl"
ITEM.replacement = "models/dizcordum/chaos/cultist/cultist1.mdl"