ITEM.name = "Edlar Clothes2"
ITEM.description = "Some clothing"
ITEM.category = "Clothing"
ITEM.outfitCategory = "Clothing"
ITEM.flag = "c"
ITEM.model = "models/weapons/w_package.mdl"
ITEM.replacement = "models/eldar_windrider.mdl"