ITEM.name = "Enforcer Lieutenant Uniform"
ITEM.description = "Standard Issue Uniform for Ship Enforcer Lieutenants"
ITEM.category = "Clothing"
ITEM.outfitCategory = "Clothing"
ITEM.flag = "c"
ITEM.model = "models/weapons/w_package.mdl"
ITEM.replacement = "models/fptp_105th_let.mdl"