ITEM.name = "Admech Clothes"
ITEM.description = "Some techsavvy clothing"
ITEM.category = "Clothing"
ITEM.outfitCategory = "Clothing"
ITEM.flag = "c"
ITEM.model = "models/weapons/w_package.mdl"
ITEM.replacement = "models/muschi/mechanicus/muschi_admech_priest_mars.mdl"