ITEM.name = "Enforcer Medical Uniform"
ITEM.description = "Standard Issue Uniform for Ship Enforcers Medical Division"
ITEM.category = "Clothing"
ITEM.outfitCategory = "Clothing"
ITEM.flag = "c"
ITEM.model = "models/weapons/w_package.mdl"
ITEM.replacement = "models/fptp_105th_guard_meh.mdl"