ITEM.name = "Enforcer Uniform"
ITEM.description = "Standard Issue Uniform for ship Enforcers"
ITEM.category = "Clothing"
ITEM.outfitCategory = "Clothing"
ITEM.flag = "c"
ITEM.model = "models/weapons/w_package.mdl"
ITEM.replacement = "models/fptp_105th_guard.mdl"