ITEM.name = "Mercenary HARK Clothes"
ITEM.description = "Some clothing"
ITEM.category = "Clothing"
ITEM.outfitCategory = "Clothing"
ITEM.flag = "c"
ITEM.model = "models/weapons/w_package.mdl"
ITEM.replacement = "models/dizcordum/wk/mercenary/croto_hark.mdl"