ITEM.name = "889th Medic Clothes"
ITEM.description = "Some clothing that is associated with mercenaries"
ITEM.category = "Clothing"
ITEM.outfitCategory = "Clothing"
ITEM.flag = "c"
ITEM.model = "models/weapons/w_package.mdl"
ITEM.replacement = "models/sc_899th_med.mdl"