ITEM.name = "Enforcer Sergeant Uniform"
ITEM.description = "Standard Issue Uniform for Ship Enforcer Sergeants"
ITEM.category = "Clothing"
ITEM.outfitCategory = "Clothing"
ITEM.flag = "c"
ITEM.model = "models/weapons/w_package.mdl"
ITEM.replacement = "models/fptp_105th_sgt.mdl"