ITEM.name = "Heavy Weapon Guardsmen Uniform"
ITEM.description = "Standard Issue Uniform for Heavy Weapons"
ITEM.category = "Clothing"
ITEM.outfitCategory = "Clothing"
ITEM.flag = "c"
ITEM.model = "models/weapons/w_package.mdl"
ITEM.replacement = "models/fptp_786th_hwt.mdl"