ITEM.name = "Veteran Medical Guardsmen Uniform"
ITEM.description = "Standard Issue Uniform for Veterans of the Medical Corp"
ITEM.category = "Clothing"
ITEM.outfitCategory = "Clothing"
ITEM.flag = "c"
ITEM.model = "models/weapons/w_package.mdl"
ITEM.replacement = "models/fptp_786th_vet_med.mdl"