ITEM.name = "Raggedy Uniform"
ITEM.description = "A uniform that is for the desperate"
ITEM.category = "Clothing"
ITEM.outfitCategory = "Clothing"
ITEM.flag = "c"
ITEM.model = "models/weapons/w_package.mdl"
ITEM.replacement = "models/fptp_786th_penal.mdl"